### ISSUE TITLE
Example payload

### ISSUE THREAD

**Issue by anohren** [facebook/FBNotifications#22]
I'm struggling to use the example payload as such. 

1. It isn't valid JSON -- I can't copy-paste and send it because there are several missing commas.
2. It's missing (?) a "version" field which makes the FBNotifications framework crash on initial tests when it tries to extract version information.

At least the framework seems to think that the version field is required. I don't know.

**Comment by nlutsenko** [comment]
Thank you for bringing it up, I am going to send a fix for it right now.
We have 5 examples built-in into the example apps.
Try using this one - https://github.com/facebook/FBNotifications/blob/master/iOS/FBNotificationsExample/FBNotificationsExample/Resources/Examples/example3.json
It renders and looks nice and this is what I am going to update the format specification to right now.
